version: '3.9'
services:
  mysql:
      init: true
      image: mysql
      ports:
          - "3306:3306"
      environment:
          - MYSQL_ROOT_PASSWORD=1234
          - MYSQL_DATABASE=polls
          - MYSQL_ROOT_HOST=%
